package com.everis.examendosacademia.model;
// Generated 20/09/2019 12:48:25 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "examen2")
public class Categoria implements java.io.Serializable {

	private int id;
	private String nombre;
	@JsonIgnore
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Categoria() {
	}

	public Categoria(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Categoria(int id, String nombre, Set<Producto> productos) {
		this.id = id;
		this.nombre = nombre;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
