package com.everis.springbootjpa.mother;
// Generated 17/09/2019 03:01:27 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "cintegracion")
public class Compra implements java.io.Serializable {

	private Integer idcompra;
	private Date fechacompra;
	private BigDecimal total;
	private int idcliente;

	public Compra() {
	}

	public Compra(Date fechacompra, BigDecimal total, int idcliente) {
		this.fechacompra = fechacompra;
		this.total = total;
		this.idcliente = idcliente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompra", unique = true, nullable = false)
	public Integer getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(Integer idcompra) {
		this.idcompra = idcompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacompra", nullable = false, length = 10)
	public Date getFechacompra() {
		return this.fechacompra;
	}

	public void setFechacompra(Date fechacompra) {
		this.fechacompra = fechacompra;
	}

	@Column(name = "total", nullable = false, precision = 7)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

}
